from zoe_exceptions.exc_non_http_internal_error import ZoeNonHttpError
from zoe_exceptions.exc_internal_exc import InternalServerException

class JWTError(Exception):
    pass

class InvalidTokenError(JWTError):
    pass

class InvalidSignatureError(JWTError):
    pass

class ExpiredTokenError(JWTError):
    pass

class InvalidAlgorithmError(JWTError):
    pass

class TokenNotYetValidError(JWTError):
    pass

class MissingIssuerError(JWTError):
    pass

class UntrustedIssuerError(JWTError):
    pass

class UnauthorizedAudienceError(JWTError):
    pass

def map_jwt_error(error: Exception) -> ZoeNonHttpError:
    if isinstance(error, InvalidTokenError):
        return ZoeNonHttpError(
            why="Invalid JWT format",
            explain="The token structure must be header.payload.signature",
            fix="Ensure the token is correctly generated and not truncated"
        )

    if isinstance(error, InvalidSignatureError):
        return ZoeNonHttpError(
            why="Invalid JWT signature",
            explain="The token signature does not match the expected signature",
            fix="Check if the secret key used to sign the token is correct"
        )

    if isinstance(error, ExpiredTokenError):
        return ZoeNonHttpError(
            why="JWT expired",
            explain="The token has passed its expiration time (exp claim)",
            fix="Generate a new token or implement refresh tokens"
        )

    if isinstance(error, InvalidAlgorithmError):
        return ZoeNonHttpError(
            why="Invalid JWT algorithm",
            explain="The token uses an unexpected signing algorithm",
            fix="Ensure the token is signed using HS256"
        )

    if isinstance(error, TokenNotYetValidError):
        return ZoeNonHttpError(
            why="JWT not yet valid",
            explain="The token cannot be used before 'nbf' time",
            fix="Check system clock or token generation logic"
        )

    if isinstance(error, MissingIssuerError):
        return ZoeNonHttpError(
            why="Missing token issuer",
            explain="The token does not contain an 'iss' claim, so its origin cannot be verified",
            fix="Ensure the token is generated with a valid 'iss' claim matching the expected issuer"
        )

    if isinstance(error, UntrustedIssuerError):
        return ZoeNonHttpError(
            why="Untrusted token issuer",
            explain="The token 'iss' claim does not match the expected issuer configured for this instance",
            fix="Verify that the token was generated by a trusted source with the correct issuer identifier"
        )

    if isinstance(error, UnauthorizedAudienceError):
        return ZoeNonHttpError(
            why="Unauthorized audience",
            explain="This service is not listed in the token's authorized audience",
            fix="Add this service identifier to the audience list when generating the token"
        )

    return ZoeNonHttpError(
        why="Unknown JWT error",
        explain=str(error),
        fix="Inspect the token and validation logic"
    )
